extends:
  - sinon

plugins:
  - ie11

rules:
  ie11/no-collection-args: error
  ie11/no-for-in-const: error
  ie11/no-loop-func: warn
  ie11/no-weak-collections: error

overrides:
  - files: "test/**/*.js"
    plugins:
      - mocha
    env:
      mocha: true
    rules:
      max-nested-callbacks: off
      mocha/no-exclusive-tests: error
