extends:
  - "@sinonjs/eslint-config"

rules:
  semi: error

overrides:
  - files: "**/*-test.js"
    plugins:
      - mocha
    env:
      mocha: true
    rules:
      max-nested-callbacks: off
      mocha/no-exclusive-tests: error
